### ISSUE TITLE
Missing `ProductDetails.priceLocale`

### ISSUE THREAD

**Issue by NachoSoto** [RevenueCat/purchases-ios#1013]
SK2's `Product` has `localizedPriceString`, but some users (including me) might need to calculate other prices, like "cost per month" for their UI. This is my app for example:

![Screen Shot 2021-11-30 at 12 50 01](https://user-images.githubusercontent.com/685609/144281130-4908b8ac-d1d6-414d-8f77-343425bbdd1a.png)

I used to calculate that like this on version 3.x:
```swift
private extension Purchases.Package {
    var pricePerMonth: NSDecimalNumber {
        let periodsPerMonth: Int = {
            switch self.product.subscriptionPeriod?.unit {
            case .day: return 30
            case .week: return 4
            case .month: return 1
            case .year: return 12
            default: return 1
            }
        }() / (self.product.subscriptionPeriod?.numberOfUnits ?? 1)
        
        return self.product.price.dividing(by: NSDecimalNumber(value: periodsPerMonth))
    }
    
    var localizedPricePerMonth: String {
        let formatter = NumberFormatter()
        formatter.numberStyle = .currency
        formatter.locale = self.product.priceLocale

        return formatter.string(from: self.pricePerMonth)! + " " + Strings.Dates.Unit.perMonth
    }
}
```

Luckily the locale is part of the `jsonRepresentation` of an SK2 `Product`.

**Comment by aboedo** [comment]
With SK1, we used to have `priceLocale`, which is meant to be used with a `NumberFormatter` so that you can format the price however you want.
In SK2, we don’t have the locale, but we do have the currency.
I think we’d be able to provide a `numberFormatter` for both SK1 and SK2, so that you can use that instead, and we set the formatter to type currency and `currencyCode` = the value from `jsonRepresentation`. This could be called priceFormatter
In addition, we could offer:
- `priceAsMonthly`, which does the $3.12 / mo thing for you
- `priceAsYearly`, etc, etc.
