### ISSUE TITLE
Optimize `priceFormatter` initialization

### ISSUE THREAD

**Issue by aboedo** [RevenueCat/purchases-ios#1033]
After https://github.com/RevenueCat/purchases-ios/pull/1028, the `priceFormatter` computed var in `StoreProduct` returns a new formatter for every product. 

This could be optimized by having a single, shared formatter, and listening for storefront changes ([Storekit 2 version here](https://developer.apple.com/documentation/storekit/storefront/storefronts#), [StoreKit 1 version here](https://developer.apple.com/documentation/storekit/skpaymenttransactionobserver/3242936-paymentqueuedidchangestorefront#)). When the storefront changes, we would reset the shared formatter, so that when the next product loads up, we create a new one.

**Comment by Juanpe** [comment]
Hi @aboedo!

I've investigated this task and I could optimize it although I'd need more info 😕 

The idea is to create a new shared price formatted that belongs to StoreProduct or create a singleton? And this new formatter gets the country code from each product or the Storefront? 

Thanks!

**Comment by NachoSoto** [comment]
`NumberFormatter` is thread-safe, but we'd need to configure it for each different currency, locale, etc.
Currently `SK1StoreProduct.numberFormatter` and `SK2StoreProduct.numberFormatter` both create a new one every time it's called, but they're expensive to create.

So I would make a private `lazy` formatter that creates it only the first time.
To avoid duplicating the caching logic I would implement this caching in `StoreProduct` which is the decorator we end up exposing.

As for invalidating this cache when the storefront changes, I'm not sure if that's super critical, but maybe @aboedo disagrees.

**Comment by aboedo** [comment]
I wouldn't consider it critical, I don't think we ever did it for SK1 in the first place. But it would be a good idea to do it sooner or later.

**Comment by Juanpe** [comment]
Thanks for the info. I'm going to try to develop a solution 👍🏼

**Comment by Juanpe** [comment]
Hi! I've investigated more about the @NachoSoto approach, I mean, placing the cache logic in `StoreProduct` but I found a problem. AFAIK, we need the `priceFormatter` to localised some prices based on current locale and currency, so could do something like that in `StoreProduct`:

```swift
// StoreProduct
@objc public var priceFormatter: NumberFormatter? { _priceFormatter }
private lazy var _priceFormatter: NumberFormatter? = {
      self.product.priceFormatter
}()
```

The problem is `SK1Product` uses internally the `priceFormatter` to localised the price. So, we can't use the cached formatter 🤔 
```swift
// SK1StoreProduct
var localizedPriceString: String {
    priceFormatter?.string(from: underlyingSK1Product.price) ?? ""
}
```

I've been thinking about it but haven't come up with an "elegant" solution...maybe my mind is a little foggy this year 😅 

A possible approach is to return an empty string for SK1 products, so `StoreProduct` will check if the string is empty, if so, it will try to format the price by itself.
```swift
// SK1StoreProduct
var localizedPriceString: String = ""

// SK2StoreProduct
var localizedPriceString: String { underlyingSK2Product.displayPrice }

// StoreProduct
@objc public var localizedPriceString: String {
    let priceString = self.product.localizedPriceString
    guard priceString != "" else {
        return priceString
    }
    
    return priceFormatter?.string(from: NSDecimalNumber(decimal: product.price)) ?? ""
}
```

As I said before I'm not proud of this solution 😓 Other approaches would be to duplicate the caching logic or create a static var, but first I'd like to share with you to know your point of view 🙂

**Comment by Juanpe** [comment]
Hi guys! Did you have a chance to review my comment with the result of the investigation of this issue/improvement? WDYT? You may have decided to put it on hold because it doesn't have as much priority now. Just to know 🙂

**Comment by aboedo** [comment]
@Juanpe Oh gosh I've no idea how we missed replying to this, I'm sorry!! 

I think we don't necessarily need the format to be shared at the `StoreProduct` level, I should have clarified that in the issue description. 

Having one formatter for SK1 and one for SK2 should be perfectly fine. For the most part, folks would use either one or the other (i.e.: if you've opted into SK2, you probably will only ever need the SK2 formatter). 

I think having those two formatters separated would simplify the solution quite a bit, right?

**Comment by Juanpe** [comment]
No problem! 🙂

> I think having those two formatters separated would simplify the solution quite a bit, right?

Yep, I'm going to prepare a PR with a proposal

**Comment by aboedo** [comment]
awesome!! Thanks @Juanpe!

**Comment by Juanpe** [comment]
Hi guys! sorry for the late reply (daddy problems 😅)

I tried to create two static (lazy) formatters, one for SK1 products and another one for SK2 products. The problem here is both are `structs` and the language doesn't allow `lazy vars` on immutable `structs`. There are some threads in the Swift forum the related to this: [thread1](https://forums.swift.org/t/allow-lazy-vars-on-immutable-structs/16417), [thread2](https://forums.swift.org/t/lazy-initialization-for-constants/15452).

This is the error:
```Cannot use mutating getter on immutable value: 'self' is immutable```

![Screenshot 2022-03-06 at 20 25 23](https://user-images.githubusercontent.com/1409041/156938901-7e3f2500-d3df-4b44-97a9-a5a49104a2cb.png)

Some possible solution that I read is we can create a mutable copy of `self` before returns the price formatter but this approach doesn't improve the performance.
```swift
var priceFormatter: NumberFormatter? {
    var copySelf = self
    let formatter = copySelf._cachedPriceFormatter
    return formatter
}
```
_More details [here](https://forums.swift.org/t/lazy-initialization-for-constants/15452/5)_

A possible solution could be the approach used in this [file](https://github.com/SDGGiesbrecht/SDGCornerstone/blob/3f3a2f90ddc4fd4f89045ef8b640a6baaa1f5a66/Sources/SDGCalendar/CalendarDate.swift#L96-L208). Basically it consists of creating an internal `class` that contains the `lazy var`. With this solution the performance is improved.

Another possible solution could be to creating a default price formatter as a singleton but to do this I would need more info about how the locale and the currency code of the Storefront could be modified. 🙁

I've created a playground to measure the performance of these approaches and the output is this:
```
-----------Tests------------
Test 1 (no cache): 159.75ms
Test 2 (cache, internal class): 47.01ms
Test 3 (copy self):  119.51ms
----------------------------
```
Here is the playground: [PriceFormatter.playground.zip](https://github.com/RevenueCat/purchases-ios/files/8193692/PriceFormatter.playground.zip)

WDYT? 🤔

**Comment by aboedo** [comment]
🤔 I think the best approach here is to go with an internal class (like a `ProductDateFormatterProvider` or something). 
So, similar to the private class approach, but I'd make a single, internal class, that provides the formatter for SK1 or SK2 as needed. The advantage to making it internal is it being testable separately. 

@Juanpe thoughts?

**Comment by Juanpe** [comment]
Sorry, when I said `internal class` I wanted to say `nested private class` 🤦🏼‍♂️ 

Yeah, I like the idea of creating a provider. My concern is if it would be thread safe 🤔 But I think my concern is because I don't know if `currencyCode` and `locale `are different for each product or if they are defined by the storefront. I mean, if I fetch the available SK1 products, they would have the same `currencyCode` and `locale`, right?

**Comment by aboedo** [comment]
They're defined at the storefront level, where they would only ever change if the storefront changes, which we can find out through https://developer.apple.com/documentation/storekit/skpaymenttransactionobserver/3242936-paymentqueuedidchangestorefront#
