### ISSUE TITLE
Add isSubscription field to StoreProduct

### ISSUE THREAD

**Issue by beylmk** [RevenueCat/purchases-ios#1295]
Based on conversation [here](https://github.com/RevenueCat/purchases-flutter/issues/320)

We can use the existence of a subscriptionPeriod to determine whether a StoreProduct is a subscription or not, and then surface this field so that users don't have to deduce type from the way in which they loaded them.

[sc-13369]

**Comment by NachoSoto** [comment]
Nice that's a good idea. Maybe it could return a `ProductType` enum instead?

**Comment by beylmk** [comment]
Yeah, that's an option, but the more fine-grained types are only available in SK2, right? Surfacing a ProductType would match our[ Android implementation](https://github.com/RevenueCat/purchases-android/blob/803eb7520d61d181828c03b8fb079a576c0fbffb/public/src/main/java/com/revenuecat/purchases/models/StoreProduct.kt#L24), though the values available would differ between Android and iOS... do you think that's okay?

**Comment by NachoSoto** [comment]
I wonder if we could just document that the data for SK1 products might be incomplete. But that way moving on SK2 data is more complete?

**Comment by beylmk** [comment]
In SK2 we'd have consumable, nonConsumable, nonRenewableSub, and autoRenewableSub...in SK1, we'd only be able to distinguish sub/non-sub, which then kinda presents a "hierarchy" of types...i.e. is sub or not -> if sub, is auto or nonRenewable, but we can only know in SK2..

The "isSubscription" just seemed like a quicker and more uniform route, but I imagine we will expose the type in iOS eventually and need to have the discussion of how to surface all the types across android and iOS.. .

@rocboronat, any feedback on what you were thinking when you opened the original issue?

**Comment by rocboronat** [comment]
Hello! That `isSubscription` will totally made it for my use case. Actually, it's what my Product wrapper I have does right now.

If I were you, I would give a `ProductType` enum instead. I would go for `enum ProductType { subscription, inApp}` today, and if some days from now you add detail to that enum, you could add a new `Product`'s attribue for the detail of the Subscription and another for the detail of the InApp if you think it has sense. Or just add more values in the `enum ProductType`.

If you think migrating to SK2 is in the near future, you could also delay this issue and do it after you have the whole set of data. And if you gave that `isSubscription` meanwhile, it'll do the job. Just take into account it's not a great data model and maybe you drop that field in the future, because we all know that if it not a subscription it's because it's an inapp purchase, but `isSubscription` is not a great name.

Well, thanks for taking the issue into consideration! 😄

**Comment by aboedo** [comment]
I agree with @rocboronat, I think having the enum `enum ProductType { subscription, inApp}` for today would already add a ton. 

Although I'd love to provide all of the SK2 values, I think it'd be problematic to have a different response in iOS 14 vs iOS 15, the code just gets more complicated and I'm not sure devs would get any value out of the extra granularity. 

Maybe we can have the `productType` that just maps to `subscription, inApp`, but add another one to `SK2StoreProduct` that bridges over the detailed value from StoreKit? That way it can only be accessed if you're guaranteed to use StoreKit 2? I'd do that as a separate thing, though, since `enum ProductType { subscription, inApp} ` would already be better than what we have today and add value

**Comment by NachoSoto** [comment]
Yeah I like that idea, have 2 enums, and derive the SK1 version from the SK2 data.
Maybe:
```swift
enum SubscriptionType {
  case subscription
  case inApp
}

enum ProductType {
  case consumable
  case nonConsumable
  case nonRenewableSubscription
  case  autoRenewableSubscription

  var subscriptionType: SubscriptionType {
    switch self {
      ...
    }
  }
}
```

Then expose both of these in `StoreProduct`, documenting that for an SK1 backed product the `ProductType` won't be complete. Thoughts?

**Comment by NachoSoto** [comment]
(Sending a proposal shortly)

**Comment by beylmk** [comment]
Closing since we've merged the iOS portion!
