### ISSUE TITLE
My own Package conflicts with RCPackage

### ISSUE THREAD

**Issue by khanov** [RevenueCat/purchases-ios#131]
Hi,

I'm trying to migrate to the new offerings system in a Swift project that has `struct Package`. It obviously conflicts with `RCPackage`, which is defined as `Package` for Swift. I installed RevenueCat via Cocoapods.

I tried to use `Purchases.Package` instead, but Xcode gives me the following error: `'Package' is not a member type of 'Purchases'`.

I'm not sure if this is an issue of RevenueCat or Swift, however I wanted to give you a heads up. I created a sample project that demonstrates the issue.

Thanks.

[ConflictingProject.zip](https://github.com/RevenueCat/purchases-ios/files/3693106/ConflictingProject.zip)

**Comment by jeiting** [comment]
Hey Khanov,

Thanks for the issue and the project. 

I think we're going to need to make Package, and some of the other export types, nested under purchases so that this works

```var packages: [Purchases.Package]? = nil```

It's a good time to make this change since it's still beta. If you want a quick hack, change line 42 in `RCPackage.h` to the following:

`NS_SWIFT_NAME(Purchases.Package)`

We'll get this rolled into the beta this week.

Jacob

**Comment by khanov** [comment]
That's what I did. Thanks, Jacob!

**Comment by vegaro** [comment]
Thanks for reporting the issue. Just made a release that should have fixed this https://github.com/RevenueCat/purchases-ios/releases/tag/3.0.0-beta.2
