### ISSUE TITLE
PurchasesDelegate is called when making purchase

### ISSUE THREAD

**Issue by Saulenco** [RevenueCat/purchases-ios#1338]
when making a purchase  `Purchases.shared.purchaseProduct`
the `PurchasesDelegate` is  also called and I ended sending to server 2 times the product/subscription

**Q1**. How can i manage this ? Can I rely always on delegate call and ignore `Purchases.shared.purchaseProduct` completion ?

also if i purchase a consumable product the product will always be available in purchaseInfo active entitlements from delegate function.
**Q2**. How can i manage this ? The only solution that i found was when a purchase is made i store the transaction and when i finish sending the data to server i finish the transaction, is there any other solution ?

**Comment by aboedo** [comment]
Hey @Saulenco, 

The delegate gets called whenever the purchaserInfo is updated, which could happen when a purchase goes through, when a renewal happens, when an entitlement gets shared through Family Sharing, etc. 

You could ignore the completion of `purchaseProduct`, or perhaps even better just ignore it only if there's no error, so that if there is an error you can communicate that to the user. 

You should use `nonSubscriptionTransactions` in `PurchaserInfo` to see the full list of all consumable purchases the user has made. 

One important thing to note from our docs is that: 
> It's important to note that at the moment, logic for keeping track of consumable redemptions must be handled outside of RevenueCat. We recommend your server is set up to receive [Webhook](https://docs.revenuecat.com/docs/webhooks) events for NON_RENEWING_PURCHASE to appropriately provide consumable content for your users.
> 
> For example: RevenueCat can track a consumable coin purchase and include it in the PurchaserInfo, but cannot track if you've granted a user the appropriate number of coins for that purchase.

Here are our docs on the matter which provide more detailed examples on how this works:
https://docs.revenuecat.com/docs/non-subscriptions

**Comment by Saulenco** [comment]
Thanks @aboedo  for your reply, it is there any possibility to send an optional`SKPaymentTransaction` in `PurchaserInfo`.

As i notice when making a purchase, or continue purchase in `handleReceiptPostWithTransaction: purchaserInfo: subscriberAttributes:error` the transaction is available and could be send to the `PurchaserInfo`.
so we could better manage the transaction.

**Comment by aboedo** [comment]
@Saulenco that's a valid consideration. We don't have the `SKPaymentTransaction` in the delegate because there might not be one in the first place, for example if the purchase was made through an Android device. 

We do however have [a field called `revenueCatId` in the Transaction](https://github.com/RevenueCat/purchases-ios/blob/3.14.1/Purchases/Public/RCTransaction.h#L16), which will give you a unique identifier, useful for tracking redemptions. 

You can obtain this through PurchaserInfo -> nonSubscriptionTransactions -> transaction.revenueCatId. 

Hopefully that should work, but let me know if there's a use case that I'm missing
