### ISSUE TITLE
Subscriptions bought througt Stripe not being updated on iOS

### ISSUE THREAD

**Issue by unxavi** [RevenueCat/purchases-ios#1380]
- [X] I have updated Purchases SDK to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/CONTRIBUTING.md)
- [X] I have searched the [Community](https://community.revenuecat.com)
- [X] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [X] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**Describe the bug**
I am buying a subscription through Stripe on the iOS app (Services being consumed outside of the app should implement payments other than IAP)

1. Environment
   1. Platform: iOS
   5. SDK version: 3.14.0
   6. OS version:  15.3.1
   7. Xcode version: 13.2.1
   8. How widespread is the issue. Percentage of devices affected. All Stripe purchases.
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior

1. User successful  buys the subscription using the stripe SDK + our backend sever
2. Stripe execute the webhook to our backend in order for us to send the receipts to RevenueCat described here: https://docs.revenuecat.com/docs/stripe
3. We send correctly the receipt to RevenueCat and we can see that the user has the entitlement on the dashboard.
4. When calling the `purchaserInfo` on the iOS SDK, this return the entitlement as inactive.

Expected behaviour would be that the entitlement is active. Which will happen if the user kills the app and opens it again. But I image this is not expected behavior.

6. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

Could be that this is related to cache? We have implemented https://docs.revenuecat.com/docs/purchaserinfo#listening-for-customerinfo-updates but this does not trigger an update, pherhaps we should have a socket connected to RevenueCat when the user has the app open?

The user just bought a subscription and the data is not refreshed, doesn't seem ideal, not sure what the issue is.

**Additional context**

**Comment by aboedo** [comment]
Hi @unxavi thanks for reporting! 

Since you also opened up #1378, I imagine that you might already have figured this out, but in case others are also running into this or you still had questions about it: 

We don't have a mechanism for the backend to push updates to the SDK when a Stripe subscription status changes, so you could hit caching issues in this case. The cache duration is 15 minutes if the app is running in the foreground. 

If you want to absolutely eliminate the possibility of this happening, like if you have a web paywall, then you'll want to either: 
- Push a background notification to your app, and then respond to the specific background notification by force-refreshing cache
- Force-refresh the cache when the paywall is closed. 

In order to force-refresh the cache, you need to do 2 things: 
- Call `Purchases.shared.invalidatePurchaserInfoCache` (or `invalidateCustomerInfoCache` in v4)
- Call `Purchases.shared.purchaserInfo()` (or `Purchases.shared.getCustomerInfo()` on v4)

**Comment by unxavi** [comment]
@aboedo I actually opened https://github.com/RevenueCat/purchases-ios/issues/1378 because I'm doing a migration but is not releated to this issue, but to another issue when running app extensions.

Anyways, then is not a bug, I have to admit that I was expecting RevenueCat doing this kind of things for us, at the end, I though the mission was to do easer the life of the developers ;)

But think about it, if you want to make our life easer, then I believe RevenueCat should have a mechanism to pushing updates to the APP. For example buying on Google play or on Stripe and that the user can see on the app on the moment.

To be honest, after the Stripe integration, I think there is many room of improvement and this is one of them, asking the developers to implements this mechanism themself I believe is getting away from the company mission, but that's just my opinion.

Maybe if you wish, we can transform this on a feature request then.

Another example for room to improvement is that we have to have a backend to listen for stripe webhook to then send it to RevenueCat. I believe RevenueCat could have a API to listen to this events directly from Stripe, would make our life easer ;) but that's another issue and another conversation.

Thanks a lot for your time, have a great weekend

**Comment by aboedo** [comment]
@unxavi that's very valid feedback, thanks! 

We have a couple of things in the oven that will make this better w/regards to specifically web paywalls and cache updates. 

Push notifications would be a good feature to add, but it does mean extra setup in terms of the app, and it would require getting permissions from the users for push notifications, which might not be desirable in many apps. 

Note that for purchases that happen on the App Store, this isn't an issue because the SDK subscribes to the payment queue so it knows as soon as a purchase goes through. 

We're thinking about ways to improve the Stripe experience as well, there are some tricky things to resolve in the case of webhooks for new purchases given that we'd have to associate them with an appUserID that the SDK knows about, but this is very much in our thoughts.

**Comment by unxavi** [comment]
@aboedo  just my two cents for ideas.

> Push notifications would be a good feature to add, but it does mean extra setup in terms of the app, and it would require getting permissions from the users for push notifications, which might not be desirable in many apps.

I agree with what you say, but is not the only tech possible to use. MQQT, HTTP/2, WebSocket, gRPC, etc. Are some  techs that could be use for server notifications without the need to ask permission for notifications to the user. Just using silent push.

>  there are some tricky things to resolve in the case of webhooks for new purchases given that we'd have to associate them with an appUserID 

What we are doing is to include the appUserID that we will send to RevenueCat as metadata on the stripe subscription information, so that when we receive the webhook from stripe, we know to which user it belongs too. This all happens in trusted enviroments. Our backend server includes the metadata, Stripe process the payment and send the webhook for example to RevenueCat and that way you call have all the necessary data.

For sure there are some downsides to all my propositions/ideas...but is my two cents from the back of my heads.

Thanks a lot.

**Comment by taquitos** [comment]
Thank you for the feedback on what we can do better integrating Strip and IAP. It's really helpful to hear from folks what is working, what isn't, and what we might do better. If you have any other ideas please feel free to let us know!
