### ISSUE TITLE
A way to know if products are cached?

### ISSUE THREAD

**Issue by fishandphil** [RevenueCat/purchases-ios#1599]
Good morning

Is there a way to know if the products are cached? So we are 100% certain that we can show our paywall without any loading time? 

It would be a function like: 

- (BOOL)areOfferingsAvailable;

To complement: 

- (void)getOfferingsWithCompletion:

We sometimes show our paywall automatically to the users when he does an action. We want to make sure that he can purchase directly, otherwise we can show something else like an interstitial advert that is already loaded.. 

I hope you understand the use-case to maximise our in-app experience.

Thank you

**Comment by aboedo** [comment]
@fishandphil let us know how it goes! I think for the most part you won't need a spinner since offerings will be in cache before you show them to the customer, because of the SDK's eager-loading behavior. 
If you absolutely want to make sure they're loaded, you can always call `getOfferings` as well, anything that happens after the completion of that method (or the async return if you're using Swift concurrency) will be guaranteed to have offerings cached.

**Comment by aboedo** [comment]
I'm closing this issue as stale, but feel free to reopen if you encounter any problems with this in practice. Have a great day!
