### ISSUE TITLE
Crash at  -[RCStoreKitWrapper paymentQueue:removedTransactions:] 

### ISSUE THREAD

**Issue by isharing0726** [RevenueCat/purchases-ios#1737]
Hi,

The below crash happens sporadically. 

Purchases SDK version: 3.10.6

Crashed: com.apple.main-thread
0  libsystem_platform.dylib       0x1f24 _platform_strlen + 4
1  CoreFoundation                 0x9114 __CFStringAppendFormatCore + 8392
2  CoreFoundation                 0x277fc _CFStringCreateWithFormatAndArgumentsReturningMetadata + 172
3  libsystem_trace.dylib          0xba40 _os_log_impl_dynamic + 180
4  libsystem_trace.dylib          0xb658 _os_log_with_args_impl + 164
5  CoreFoundation                 0x62f68 _CFLogvEx3 + 184
6  Foundation                     0x455a0 _NSLogv + 120
7  libswiftFoundation.dylib       0x1cae4 specialized withVaList<A>(_:_:) + 440
8  PurchasesCoreSwift             0x14284 $s18PurchasesCoreSwift6LoggerC3log5level7messageyAA8LogLevelO_SStFZTf4nnd_n + 324
9  PurchasesCoreSwift             0x14114 $s18PurchasesCoreSwift6LoggerC5debugyySSFZToTm + 120
10 Purchases                      0x26e94 -[RCStoreKitWrapper paymentQueue:removedTransactions:] + 620
11 libdispatch.dylib              0x63094 _dispatch_call_block_and_release + 24
12 libdispatch.dylib              0x64094 _dispatch_client_callout + 16
13 libdispatch.dylib              0x10d44 _dispatch_main_queue_drain + 928
14 libdispatch.dylib              0x10994 _dispatch_main_queue_callback_4CF$VARIANT$mp + 36
15 CoreFoundation                 0x4e0c4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
16 CoreFoundation                 0xb5e8 __CFRunLoopRun + 2544
17 CoreFoundation                 0x1e240 CFRunLoopRunSpecific + 572
18 GraphicsServices               0x1988 GSEventRunModal + 160
19 UIKitCore                      0x4e541c -[UIApplication _run] + 1080
20 UIKitCore                      0x27eb88 UIApplicationMain + 336
21 iSharing                       0x19120 main + 15 (main.m:15)
22 ???                            0x105ee83d0 (Missing)

**Comment by aboedo** [comment]
Hey @isharing0726, thanks for opening. 

Could you try upgrading to the latest version? 3.10.6 is pretty old, it was released over a year ago, and we've issued a lot of improvements and bug fixes since then. It's likely that upgrading will fix this crash. 

You should be able to migrate to 3.14.2 without making any changes on your app. 

However, we also released a new major version with several additions and improvements, the latest version available is 4.6.1. Upgrading to that one will require small changes in your app. Most of them will be automatically suggested by Xcode, [here's our migration guide in case you're interested](https://revenuecat.github.io/purchases-ios-docs/4.6.1/documentation/revenuecat/v4_api_migration_guide).

**Comment by aboedo** [comment]
I'm closing this issue for now, but feel free to reopen if you run into any issues while upgrading!
