### ISSUE TITLE
 'Purchases' is not a member type of 'Purchases'

### ISSUE THREAD

**Issue by kerimdeveci** [RevenueCat/purchases-ios#197]
Hi, i recently updated my Purchases pod version 2.6 to 3.0.4. I also changed getting offerings method to this :  
```swift
Purchases.shared.offerings { (offerings, error) in
            if let packages = offerings?.current?.availablePackages {
                // Display packages for sale
            }
}
``` 

but i couldn't be able to get current offerings.
i tried to delete derived data , deintegrating pods and installing again, deleting build folders, but no conclusion.
the error is : 
```
Printing description of offering:
expression produced error: error: /var/folders/4g/w58ds9mx2l77zy4fzbd97jyw0000gn/T/expr11-5be3e6..swift:1:90: error: 'Purchases' is not a member type of 'Purchases'
Swift._DebuggerSupport.stringForPrintObject(Swift.UnsafePointer<Swift.Optional<Purchases.Purchases.Offerings>>(bitPattern: 0x1154b4450)!.pointee)
                                                                               ~~~~~~~~~ ^
````

**Comment by aboedo** [comment]
I'm a bit perplexed here - I just tried this code on the sample app and it ran with no issues on 3.0.4. 
How are you importing Purchases? Also, are you specifying the type `Purchases.Offerings` anywhere on your code?

**Comment by kerimdeveci** [comment]
i was not specifying the type `Purchases.Offerings` and yes i imported Purchases. This is an old project updated to v3.0.4 Purchases.  
I think problem occurs with my cocoapods setup. or maybe offerings arranged on revenucat portal with old version?
Anyway i downgraded my versions to 2.6 . now using 2.6 with no problem . i get entitlements with 
```swift
Purchases.shared.entitlements({ (entitlements, error) in
        // entitlement get here       
})
```
this method. 
thank you very much for answering.

**Comment by aboedo** [comment]
I just ran into this: repro'd by using "print description" from Xcode on the offerings object. 
In my case, it doesn't happen if you just print through either code or through `po`. 
I believe it might be related to this known bug in Xcode: https://forums.developer.apple.com/thread/123253

**Comment by kerimdeveci** [comment]
it might be this issue coz i encountered this problem in this project many times.  thank you very much again

**Comment by aboedo** [comment]
it seems like the underlying issue is that there's an inconsistency in lookup strategies, where depending on the case the lookup of Purchases.Purchases.Offerings might be targeting either the module or the class. 
This would ordinarily not be a problem, but given that both the framework and the class have the same name, it can lead to this issue. We're studying alternatives. 

In the meantime, could you share a bit more of the code that reproduced the issue? 
It seems like in the trace you shared you might also have been printing out from xcode, like I was. 
did you get any other issues? what happens if you programmatically do something like: 

```swift
guard let offerings = offerings else { fatalError("offerings was nil") }
print(offerings)
```

If that actually shows something, then the issue might have been some misconfiguration around offerings
