### ISSUE TITLE
Purchaser info not returning correct "isActive" value for entitlement on WatchOS

### ISSUE THREAD

**Issue by imtherb91** [RevenueCat/purchases-ios#224]
I am running v3.2.2 on my iOS and WatchOS targets with the same appUserID value. After making a sandbox subscription purchase on iOS, the purchaserInfo on iOS returns the correct entitlement with "isActive" true. However on WatchOS, it returns that same entitlement with "isActive" false. 

Oddly enough, WatchOS does list the expirationDate as a time in the future, indicating it is an active entitlement. Any suggestions for a work around on this? I'm thinking of using the expirationDate value for WatchOS purchase validation only.

**Comment by imtherb91** [comment]
Update: it eventually did begin returning isActive = true on WatchOS. There must just be about a 10 min delay between iOS and WatchOS?

**Comment by aboedo** [comment]
🤔 Is this behavior consistent? 

If so, I _think_ this might be a case where the watch app had cached purchaser info. 
The apps are independent as far as RevenueCat data goes, so they'll each have a purchaser info cache. 

One way to test if this is the case is to: 
- start watch app
- start iphone app
- buy on iphone
- watch app will not know about the purchase yet
- terminate watch app (press the side button on the watch and then swipe left on the app)
- start watch app again, info should refresh quickly now. 

please confirm if that is the case. If it is, there's a workaround for this: 
right after the purchase has been made (and only after it has been made successfully), 
you need to [send a message to your watch app from your iOS app](https://developer.apple.com/documentation/watchconnectivity/wcsession/1615687-sendmessage?language=objc) telling it that a purchase has been made. 
once the watch app receives this message and *only if the app is already open*, you can call `Purchases.shared.invalidatePurchaserInfoCache()`. 
The cache should refresh. **Please note that this method should only be called in this special type of circumstance**, since for almost any other case the SDK will do effective cache management on its own.

**Comment by imtherb91** [comment]
Ah that makes sense, yep that must have been it. Thank you very much for the in-depth response!

**Comment by aboedo** [comment]
glad the info helped. I'm closing this out for now, but feel free to reopen if you run into any more issues with it
