### ISSUE TITLE
Purchase made on watchOS seems doesn't track Apple Search Ads attribution

### ISSUE THREAD

**Issue by Turacbey** [RevenueCat/purchases-ios#2366]
- [*] I have updated Purchases SDK to the latest version
- [*] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/Contributing/CONTRIBUTING.md)
- [*] I have searched the [Community](https://community.revenuecat.com)
- [*] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [*] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

Scenario;
1- Using iPhone, user installs the app from the App Store and open it (so revenuecat identify the user etc.)
2- User open the app from his/her Apple Watch and make a purchase from there

**Comment by joshdholtz** [comment]
@Turacbey Heyy 👋 Thanks for bringing this up! This is kind of weird issue and great question so hopefully I can shed some light on this and we can get this working for you.

## Problem

watchOS doesn't support [fetching the attribution tokens](https://developer.apple.com/documentation/ad_services/aaattribution/3697093-attributiontoken) (which you may know but wanted to clarify anyway for anobody else that comes across this issue). It's only supported on iOS and macOS. This means that the user does have to open the iOS app first as your scenario suggest which is correct 💯 

However, an iOS app and watchOS app have different App Store receipts which means that RevenueCat will initially identify them as two separate users (the SDK will give them different anonymous ids).

So _if_ you are only using the RC anonymous user ids, the attributed purchases through ASA would make sense.

## Solution

I _think_ the solution here would be to call `Purchases.shared.logIn(appUserId)` with the same app user id in both your iOS and watchOS app.

This would require using something like the [Watch Connectivity framework](https://developer.apple.com/documentation/watchconnectivity) to send the app user id from the iOS app to the watchOS app. After that, the watchOS app would call `Purchases.shared.logIn(appUserId)`. This would tell the RevenueCat backend that the users are the same and that a purchases from the watchOS app would be linked to the attribution token.

FWIW... I have not tested out this solution myself (yet) but wanted to send it your way first since it might be quicker for you to try it out if you aren't already doing it. I do have some personal apps on the App Store that I can test this with but one doesn't have a watch app published yet (development is in the works). 

But hopefully this clears up why this is probably happening and with a possible solution!

**Comment by Turacbey** [comment]
@joshdholtz Heyy, thank you very much for your fast response and the solution.

I'm excited to test it out!

**Comment by Turacbey** [comment]
@joshdholtz Hello!

Do I really need to use Purchases.shared.logIn?
Isn't it enough to use same custom id for initializing Revenuecat for both devices?
