### ISSUE TITLE
periodType = null in test environment.

### ISSUE THREAD

**Issue by pangia** [RevenueCat/purchases-ios#239]
The periodType in active entitlements is null. This is during sandbox testing with the latest version 3.2.2.  If this is due to the sandbox, is there a way we can test to ensure it works in production?

**Comment by aboedo** [comment]
`periodType` should behave normally in sandbox. This might be due to a configuration issue. 
Things to check: 
- is the product a subscription? `periodType` isn't meant for consumables
- is the product that was purchased correctly configured in the RevenueCat dashboard and attached to an offering? 

if both of those are true or you have questions about how to perform that setup correctly, please [refer to our docs ](https://docs.revenuecat.com/docs) and / or [reach out to our support team](https://support.revenuecat.com/hc/en-us) who'll be better able to assist you.

**Comment by pangia** [comment]
Sorry for the delayed response. I found my issue. in the purchaseInfo.entitlement objects it was showing as null for some reason, but when referenced directly using "purchaserInfo.entitlements.all[@"Memberships"].periodType" it is populated correctly. This can be closed.

**Comment by aboedo** [comment]
thanks for the update! glad it's working 😃
