### ISSUE TITLE
Background task not cancelled and exceeding 30 seconds

### ISSUE THREAD

**Issue by WillBishop** [RevenueCat/purchases-ios#250]
On a slower connection or a turbulent one (such as one with DNS lookup issues), the SDK does not seem to time out background requests are 30 seconds

This results in the error:

> 2020-05-18 12:37:41.506064+0930 AppName[614:141029] [BackgroundTask] Background Task 31 ("SKProductsRequest"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.

And if this were in the background, it'd cause an app crash.

**Comment by aboedo** [comment]
thanks for bringing this to our attention, we'll improve the behavior of background tasks so that this doesn't happen anymore. I'm keeping the ticket open until we have a fix out.

**Comment by aboedo** [comment]
upon further inspection, I'm not sure there's much we can do here - management of the SKProductsRequest happens on iOS. 
For normal [background tasks](https://developer.apple.com/documentation/uikit/uiapplication/1623031-beginbackgroundtaskwithexpiratio?language=objc), you'd pass in a handler that gets called just before the timer for the task expires, so that you can cancel the task and clean up. 
However, the task itself is managed by iOS, and we can only call start and provide a delegate for success and failure. 
Furthermore, although it looks like the `SKProductsRequest` is using the UIApplication backgroundTask mechanism, it doesn't seem to be explicitly documented (or I couldn't find where), so we can't really make assumptions as for how it works in order to perform better cleanup. 

I assume that this is something that iOS itself will eventually clean up in a newer release.

**Comment by aboedo** [comment]
I'm closing this issue for now, but feel free to reopen if I missed something.
