### ISSUE TITLE
Trying to purchase an already purchased/active subscription

### ISSUE THREAD

**Issue by renjithn** [RevenueCat/purchases-ios#252]
This is not an issue with the SDK but a question on how a certain behaviour should be handled.
Been using SwiftyStoreKit for a while but planning to shift to RevenueCat. I'm wondering how this [scenario](https://github.com/bizz84/SwiftyStoreKit/issues/125) can be handled. 

TLDR; When a user tries to purchase a subscription that is already active, StoreKit, despite  showing an "you're already subscribed" dialog, returns a "SKErrorDomain Code=2" (Payment Cancelled). With SwiftyStoreKit, when this happens one could refetch the receipt (with `fetchReceipt(forceRefresh:)`, validate and then let the users know if the subscription is already active. 

Not sure whether the equivalent method in RevenueCat `Purchases.shared.purchaserInfo { purchaserInfo, _ in}` works here?

**Comment by aboedo** [comment]
Hi! 👋 
We try to reserve GitHub issues for bug reports only. Our support team (reachable through[ our support page](https://support.revenuecat.com/hc/en-us)) is better-equipped at providing assistance for configuration and usage. Please reach out to them to get better assistance. 

For your case, you should be able to use the `purchaserInfo` to find a user's active subscriptions. If this is a new device / the receipt on the device need to be refreshed, you can use `restoreTransactionsWithCompletionBlock` to refresh. Note that this may prompt for apple id sign-in, so it should be ideally tied to a user action and not triggered automatically on launch. 

I'm going to close the ticket since this isn't a bug, but feel free to check out our [support page](https://support.revenuecat.com/hc/en-us) if you need further assistance with this.

**Comment by yasirmturk** [comment]
It is actually a bug in `SwiftyStoreKit` as `SwiftyStoreKit.purchaseProduct` gets lost and does not even give a callback `result` and just prints a message in console.. something like
```
Unexpected restored transaction for payment <>
Finishing transaction for payment "<>" with state: restored
```
so as a user we can not even suggest the user to try restore...
