### ISSUE TITLE
Swift paywall rejected by App Store

### ISSUE THREAD

**Issue by alamodey** [RevenueCat/purchases-ios#301]
Just wanted to let you know that the example Swift paywall gets rejected by the App Store:
_Guideline 3.1.2 - Business - Payments - Subscriptions

We noticed that one or more of your auto-renewable subscriptions is marketed in the purchase flow in a manner that may mislead or confuse users about the subscription terms or pricing. Specifically:

- Your auto-renewable subscription displays the monthly calculated pricing for your subscription more clearly and conspicuously than the billed amount.

- The billed amount of your auto-renewable subscription is not clearly and conspicuously displayed to the customer._ 

Luckily it's an easy fix by changing the font size of the monthly amount.

Side note, the paywall looks like it isn't using all the space effectively. How do I add my app's icon/logo to fill up the space at the top?

**Comment by aboedo** [comment]
Hey @alamodey could you share a screenshot of what your paywall looks like with all data filled?
This is what the sample looks like on our testing RevenueCat app: 
![IMG_BBBB30EB2D91-1](https://user-images.githubusercontent.com/3922667/88930243-9576db80-d251-11ea-9eab-c9624b044556.jpeg)

In this case, you can see that the $39.99 price is displayed in a larger font and more prominent color than the monthly price. Does your screen match this structure?

**Comment by alamodey** [comment]
This is the updated paywall that got approved after I adjusted the fonts:

By the way, the 33% discount in your screenshot, is that automatically
displayed if you created an introductory price in your subscription or do
you need to manually add it to the paywall?

**Comment by aboedo** [comment]
@alamodey did you manage to figure this out?

**Comment by alamodey** [comment]
![Simulator Screen Shot - iPhone 11 - 2020-08-05 at 21 49 17](https://user-images.githubusercontent.com/55496019/89409513-89b17a80-d765-11ea-99d1-c17e68f8cd4b.png)
I shrinked the monthly rate further and it got approved. 

By the way, how do I add an image at the top to use up some of the blank space? Can you update your paywall to put a placeholder?

**Comment by aboedo** [comment]
I'm glad it got approved! 

Our paywall is meant to serve mostly as a reference and an example, but it's not meant to be usable as-is for apps. It can be adapted, of course, as you have, but we're not focusing developing it further for the time being. 

As for adding an image at the top, I suggest adding a `UIImageView` to the top by either moving the `headerView` down (i.e.: altering its top constraint), or adding the `UIImageView` to it, then positioning it within the bounds and setting the aspect ratio. 

I'm closing this issue since it got solved. 

I'd recommend [this guide by Apple](https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/AutolayoutPG/index.html) and this [Ray Wenderlich post](https://www.raywenderlich.com/811496-auto-layout-tutorial-in-ios-getting-started) for further help with AutoLayout. 

Also, since programmatic constraints can be a hassle to write, I highly recommend using [SnapKit](https://github.com/SnapKit/SnapKit) to write constraints easily (if you're doing them programmatically). They also have an objective-c library that's very similar called Masonry.
