### ISSUE TITLE
Offerings/purchaserInfo no longer synchronously returned from cache via main thread

### ISSUE THREAD

**Issue by wsun** [RevenueCat/purchases-ios#401]
**Describe the bug**
A small change in 3.7.4 now has `purchaserInfo` and `offerings` returning from cache on DispatchQueue.main async instead of the main thread. I understand apps shouldn't depend on a synchronous main thread return here, but it'd be nice if it could when possible, and it seems like it can without disrupting current behavior.

1. Environment
    1. Platform: iOS
    2. SDK version: 3.7.4
    3. OS version: 14.1
    4. Xcode version: 12.1
    5. How widespread is the issue. Percentage of devices affected. 100%

3. Steps to reproduce, with a description of expected vs. actual behavior
Call `Purchases.shared.purchaserInfo` when a cached value is present, and now it returns just a bit slower on async DispatchQueue.main

4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)
Relevant change was in this commit: https://github.com/RevenueCat/purchases-ios/commit/38d16aa9d59b5204f22f7cbdac627d3699b3f623
Specifically, `purchaserInfoWithCompletionBlock` and `offeringsWithCompletionBlock` now asynchronously request application background state before returning a cached value. Previously, this application state was requested after cache return. Since application state seems to only be necessary when updating a stale cache or no cache, proposed fix would be to shift the background state request after cache return and to the else-block when no cache is present.

**Comment by aboedo** [comment]
I'm not sure I understand the issue here: `DispatchQueue.main` is a queue that's directly associated with the main thread by the OS (as documented here https://developer.apple.com/documentation/dispatch/dispatchqueue/1781006-main), so there return will still be on the main thread. 

As for the slowness, yes, it does unfortunately return slightly slower than before. This is because of some new app state checks, that unfortunately need to run on the main thread (because they're done on `UIApplication`), so there's a bit more back and forth between a worker thread and the main thread. 

Those checks are tied to the app state, because the state is also used to determine whether a refresh is needed, so there's no clean way of disassociating them.

**Comment by wsun** [comment]
Sorry I probably didn't make it too clear - yup I was primarily highlighting how previously it was returned synchronously on the main thread, you are right that right now it's dispatched asynchronously to the main thread as well. I understand you have the app state checks in place, but it doesn't seem the app state check is strictly necessary for the cache return (it seems like it is for a cache refresh).

For example, [L425](https://github.com/RevenueCat/purchases-ios/blob/4190aceade7ea7aaaecf6dd3cb54bd57f43f2c5e/Purchases/Public/RCPurchases.m#L425) for `purchaserInfoWithCompletionBlock` seems like it could be after L429 instead of where it is right now (and I guess before L436 since it is necessary there too).

Anyway this is a small change that we observed in our UI animations - not critical, but assuming I'm reading this code correctly, could be an easy perf improvement with no change to the existing functionality.

**Comment by aboedo** [comment]
@wsun great catch, you're correct and we could improve those. I'll add it to the backlog. Thanks for pointing this out!

**Comment by aboedo** [comment]
addressed in https://github.com/RevenueCat/purchases-ios/pull/433
