### ISSUE TITLE
Customer Center UI feedback

### ISSUE THREAD

**Issue by unxavi** [RevenueCat/purchases-ios#4355]
Hi,

After start testing the customer center, we would like to give you the following UI feedback:

- Have more flexibility adjusting text styles (bold, regular)
- Have more flexibility with the alignment of the texts, it looks off to have the title centered but the description aligned to the left
- Have more flexibility adjusting paddings, right now the content starts too close to the page and there's a big gap between the title and description

![Screenshot 2024-10-03 at 13 04 02](https://github.com/user-attachments/assets/c9e9805a-efe3-4dbd-91fa-d68c1a2f0c2f)

**Comment by aboedo** [comment]
@unxavi thanks for the feedback! All very valid, we'll look into the best ways of doing this

**Comment by aboedo** [comment]
Our current thinking is to take this in a couple of steps: 
- the "no thanks" button should map to the colors selected in the dashboard, that was a bug
- we like your spacing for title and subtitle and the padding much better than the current implementation so we'll go with that for now
- a future version will make all of this customizable, but I don't have an ETA for it yet

**Comment by vegaro** [comment]
@unxavi I am going to close this since the "no thanks" button color bug has been fixed and I've just merged #4369 which applies similar spacing to the one you reported to the promotional offer view

As Andy mentioned, making all this customisable will be possible at some point in the future, but we don't know when that'll be prioritised

Thanks so much for the feedback, we really appreciate it. Let us know if you have any other and we'll look into it.
