### ISSUE TITLE
Building project on M1 macs

### ISSUE THREAD

**Issue by mmdumi** [RevenueCat/purchases-ios#450]
Hi,
Carthage is ready to compile frameworks as xcframework in order for us to run projects on M1 macs.
Can you please compile the project as an xcframework ? 
Thank you

**Comment by aboedo** [comment]
compiling as xcframework with compatibility for all platforms is unfortunately tricky, although it is definitely in the roadmap. 

However, you should still be able to compile the framework with carthage by doing: 

```bash
carthage update --no-use-binaries
```

There is a caveat, though: carthage has some compatibility issues with Xcode 12. So in order to get that command to work, you will likely have to use the [workaround suggested by the carthage team](https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md), which involves creating a script that you use to invoke carthage, i.e.: 

```bash
<path_to_carthage_workaround_script>/carthage.sh update --no-use-binaries
```

**Comment by aboedo** [comment]
@mmdumi have you given the approach described above a shot?

**Comment by mmdumi** [comment]
Yeah, that workaround shouldn't be applied as that excludes the arm64 arch for simulator which means that it will not work on simulator on m1 macs.
What I did for now is to manually compile Pruchases.xcframework from the project.

**Comment by aboedo** [comment]
right, that does make sense. 
I do hope to get xcframeworks support for Carthage soon. This is all fairly new, since Carthage itself didn't use to support it until very recently. 
I believe the other package manager options (SPM and Cocoapods) should be able to correctly handle simultaneous support for Apple Silicon and Intel macs. 
And you can also of course just build from source, like you mentioned.

**Comment by aboedo** [comment]
@mmdumi I just realized that building through carthage with `--no-use-binaries` right now has some issues that are actually unrelated to architectures, we'll be fixing those soon. 
I've added a `.xcframework` version of the SDK into the github release in the meantime, but for proper carthage support on Apple Silicon I'm afraid we'll have to wait until we solve the `--no-use-binaries` issues. 
Unfortunately, running `carthage update --use-xcframeworks` seems to ignore the `.xcframework` that's already been uploaded.

**Comment by aboedo** [comment]
GitHub auto-closed this issue because I referenced it in the PR, but I'm going to keep it open just a bit longer until a release is out with the fix.

**Comment by aboedo** [comment]
okay, closing this one now because version `3.10.5` has been released with support for XCFrameworks on Carthage! 

To use this: 
- make sure you're using Carthage >= 0.37
- make sure to pass in both `--no-use-binaries` and `--use-xcframeworks` to Carthage, i.e.: 
```
carthage update --no-use-binaries --use-xcframeworks
```
- if you're just transitioning to XCFrameworks with Carthage, make sure to [follow the migration steps on Carthage's website](https://github.com/Carthage/Carthage#migrating-a-project-from-framework-bundles-to-xcframeworks), which include deleting the Carthage/Build folder and the related build phases. 

Thanks @mmdumi for opening this issue and bringing it to our attention!
