### ISSUE TITLE
Warning: Accent color ‘AccentColor’ is not present in any asset catalogs.

### ISSUE THREAD

**Issue by Yrban** [RevenueCat/purchases-ios#462]
1. Environment
Platform: Mac
SDK version: 3.10.3
OS version: macOS 14.2 (Big Sur)
Xcode version: 12.4
How widespread is the issue: Build Warning for project.

2. [Debug logs] None
3. Build for App Store Connect
4. **Other information** Located in Purchases/IntegrationTests/CommonFiles/Assets.xcassets. AccentColor is defined but left blank, causing the warning.

**Comment by aboedo** [comment]
Hi! thanks for reporting. When / where is the build warning shown? Are you using a package manager? If so, which one? 
I'm asking because the `IntegrationTests` aren't meant to be used outside of the context of integration tests for the SDK before deploying new versions, so I hadn't expected that build warnings for them would show up to devs using the SDK.

**Comment by Yrban** [comment]
The warning is shown when building for ARM 64 to deploy to the App Store. This is using SwiftPackages in Xcode.

**Comment by AnatoliyOstapenko** [comment]
Hi guys! Did you can solve the issue.

I have the same.

**Comment by PolarMishka** [comment]
I had this when I unintentionally deleted AccentColor. Just added it back from an empty project.

**Comment by aboedo** [comment]
@AnatoliyOstapenko I can't reproduce this issue locally using Swift Package Manager and 3.11.1. Is the error message pointing to `Purchases/IntegrationTests/CommonFiles/Assets.xcassets.` in your case?
