### ISSUE TITLE
Migrate RCLogUtils

### ISSUE THREAD

**Issue by taquitos** [RevenueCat/purchases-ios#538]
This will probably be the last one migrated.

**Comment by aboedo** [comment]
This file is actually just a backwards-compatibility utility for when we migrated logging to Swift in the first place a while back, so that we wouldn't have to update all existing calls to logging. So all that's needed here is to delete the file when existing calls to it are migrated to swift. I'll update the title

**Comment by aboedo** [comment]
gonna take care of this one! I'll remove the macros and replace with calls to the logger directly. That'll make migrating other files easier.
