### ISSUE TITLE
Migrate RCProductInfoExtractor

### ISSUE THREAD

**Issue by taquitos** [RevenueCat/purchases-ios#564]

**Comment by Juanpe** [comment]
If it's still available, I'll do it :)

**Comment by taquitos** [comment]
Feel free 😄 It's available

**Comment by Juanpe** [comment]
Hi @taquitos, I've got a question.

I'm migrating the product extractor, but I've realized that the `currencyCode` value is mandatory to create a `ProductInfo` object. The problem is that the `currencyCode` property returns an optional ([`Locale+Extensions.swift:12`](https://github.com/RevenueCat/purchases-ios/blob/swift_migration/PurchasesCoreSwift/FoundationExtensions/Locale%2BExtensions.swift)). 

Although I can't imagine any scenario where this property is `nil`, how should we consider it? I'm not sure if we should force unwrap this property or throw a fatal error...

**Comment by taquitos** [comment]
Ooooo I'll take a look tomorrow morning 😁
