### ISSUE TITLE
Please add ability to hook in a custom logger

### ISSUE THREAD

**Issue by jbb1003** [RevenueCat/purchases-ios#84]
Currently RCSetShowDebugLogs(YES) will cause logging to go to NSLog. We (and presumably a lot of other people) have our own logger, and we would prefer to have logging routed through it. 

The MVP for this is something like RCSetLoggingFunction(void *fn);

**Comment by vegaro** [comment]
Thanks @jbb1003 for requesting this. I have added the request to our public roadmap https://trello.com/c/GgtROh5V/63-custom-logger-function-in-ios-and-android and will be closing this since it's more than a feature request than an issue. You can upvote the request in that public trello board.

Thanks again!

**Comment by lordzsolt** [comment]
@vegaro What was the outcode? 

The trello board is private, so I cannot see if it's completed or not.
And looking at the Swift interface, I don't really see any way to hook in a custom logger.

**Comment by vegaro** [comment]
We do have a way to hook up a custom logger now via the logHandler static property

https://revenuecat.github.io/purchases-ios-docs/4.43.1/documentation/revenuecat/purchases/loghandler
