### ISSUE TITLE
APITesters use SPM, is this what we want?

### ISSUE THREAD

**Issue by taquitos** [RevenueCat/purchases-ios#857]
Issue to track a discussion around using SPM in our APITester project.
Right now we use SPM for both the ObjC and Swift APITester. This means it doesn't check our API in realtime as we edit it, but rather, only at CI time. Should we, instead do something like creating a RC workspace with these projects and then depend of RC project instead of SPM?

**Comment by beylmk** [comment]
@taquitos copying from a comment on PR:

As of now they just use SPM because it's the first integration I tried 🤷 I was considering trying to create testers using carthage and cocoapods as well, at least for testing the migration guide locally. That's where @taquitos was helping me figure out how to have a shared folder between different xcode projects, so hopefully only the integration piece needs to be separate.

Longer term, I see the API testers as purely testing our API...there wouldn't be any differences in our API between integrations, right?

**Comment by taquitos** [comment]
Discussed offline, yes!
