### ISSUE TITLE
Network calls during configure process

### ISSUE THREAD

**Issue by Out1and3r** [RevenueCat/purchases-ios#86]
As soon as configure function is called library is making 2 network calls. This is a new logic and wasn't there before. Is it a bug or there is reasoning behind this decision?

**Comment by jeiting** [comment]
This is normal.

1. First one is to fetch the subscription status for the configured user.
2. Second one is to fetch the available products and and entitlements.

Eventually we'll probably consolidate these to one request. Alternatively, we could enable `HTTPShouldUsePipelining` on `NSURLConnection` which would put both requests on the same TCP connection.

**Comment by Out1and3r** [comment]
This is breaking single responsibility principle. Config function should be responsible for init only. Is there a way I can init class without making outside calls?

**Comment by jeiting** [comment]
Yeah, we do this to ensure this info is ready as soon as possible.

If you are trying to write code that is strict about side effects I'd create your own wrapper class that you can init that defers the configure call until you want to do the initialization.

**Comment by Out1and3r** [comment]
So previously I had to do config and then call get entitlements(2 lines) in any place that would suit my code. Now 1 line of code but without a way to choose...

Write a wrapper to manage another wrapper...

**Comment by jeiting** [comment]
I'm not sure I understand. 

You should only need to call `configure` once ever. You can then call `entitlements` when you need them, the `configure` starts the request so that hopefully they are already cached when you need them.

Why does the internal HTTP calls of configure affect your code? It shouldn't matter to the SDK user.

**Comment by Out1and3r** [comment]
I will use analogy: NSURLSession does not fire network call as soon as it is inited to create cache for a user.
I understand what you are trying to achieve. Pre cache so the actual call "get entitlements" would be faster. My problem is: unexpected library network calls at the stage they should not be launched.
My understanding: you can change class properties in any way before you start actual use. I can reconfigure NSURLSession in any way I want before making any actual network calls.
P.S. I can't find change log for version 2.0. Could you please point me.

**Comment by jeiting** [comment]
Thanks for feedback. We try to build the easiest to use API that will provide the best end user experience. Sometimes that means doing things that you wouldn't do in a more narrow framework like `NSURLSession`. Obviously, it doesn't always fit everyone's codebase perfectly. 

The SDK is open source, and you're welcome to fork and adjust to fit your style if that's important.

Here's the code diff for the 2.0 release. We haven't written a migration guide because we weren't really sure how many people would make the leap. Perhaps that is something we should invest in.
https://github.com/RevenueCat/purchases-ios/compare/1.2.1...2.0.0

Let me know if you have any questions about the migration. We're usually able to answer quickly on our on-site chat. :)

**Comment by ashish-naik** [comment]
I tried below and error went away !!
1. Went to Pods -> Info -> Configurations -> Debug
2. Change to None for Pods-SwiftExample

Can compile even after setting it back to original.

Can see the products page.

Ashish
