### ISSUE TITLE
checkTrialOrIntroductoryPriceEligibility returns "RCIntroEligibilityStatusEligible" when there are no intro offers

### ISSUE THREAD

**Issue by haarj** [RevenueCat/purchases-ios#982]
- [ -] I have updated Purchases SDK to the latest version
- [- ] I have read the [Contribution Guidelines](https://github.com/RevenueCat/purchases-ios/blob/main/CONTRIBUTING.md)
- [- ] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [ -] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [ -] I have searched for [existing Github issues](https://github.com/RevenueCat/purchases-ios/issues)

**Describe the bug**
Every time I call the "checkTrialOrIntroductoryPriceEligibility" API I get a status of "RCIntroEligibilityStatusEligible" but I don't have any introductory offers or promotional offers in App Store connect. I used to but I deleted them. 

1. Environment
   1. Platform: iOS
   2. SDK version: 3.13.0
   3. OS version: 15.1.1
   4. Xcode version: 13.1
   5. How widespread is the issue. Percentage of devices affected. All
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
[Debug_logs.txt](https://github.com/RevenueCat/purchases-ios/files/7576321/Debug_logs.txt)

3. Steps to reproduce, with a description of expected vs. actual behavior
In IntroEligibilityCalculator.swift line 42,
            let receipt = try receiptParser.parse(from: receiptData)
I po JSONSerialization.jsonObject(with: receiptData, options: .allowFragments)

and get this error
Error Domain=NSCocoaErrorDomain Code=3840 "Garbage at end around line 1, column 1." UserInfo={NSDebugDescription=Garbage at end around line 1, column 1., NSJSONSerializationErrorIndex=1}
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Additional context**

**Comment by haarj** [comment]
1 more thing to know is that 1 product ID is "Waiting for Review"

**Comment by aboedo** [comment]
Hi @haarj! 👋 
Thanks for reporting! The logs are very helpful, we're going to look into it. 

For context, I believe that the is that when we can't compute introductory eligibility on device (when parsing the receipt fails if the receipt format is unexpected, for example when using storekit configuration files), we fall back to computing eligibility on the backend, but the backend doesn't have information regarding the existence of intro offers for products, since this information is sadly not available on the receipt or the App Store Connect API. 

However, we can solve this by merging the backend response with the information for intro offers that we can obtain on device.

**Comment by haarj** [comment]
You're the doctor @aboedo . ;)

**Comment by haarj** [comment]
Also @aboedo is it possible to make attachments private and only visible to RevenueCat people? There could be sensitive information that I or anyone may inadvertently share here.

**Comment by haarj** [comment]
no problem
