### ISSUE TITLE
replace `ISO8601DateFormatter` with the one from Foundation

### ISSUE THREAD

**Issue by aboedo** [RevenueCat/purchases-ios#988]
We're currently creating a `DateFormatter` instance and [setting the format manually](https://github.com/RevenueCat/purchases-ios/blob/main/Purchases/FoundationExtensions/DateFormatter+Extensions.swift#L19), but now that we've dropped support for iOS 9.0, we should be able to replace that with [ISO8601DateFormatter](https://developer.apple.com/documentation/foundation/iso8601dateformatter#)

https://app.shortcut.com/revenuecat/story/11210/remove-custom-iso8601-date-formatter

**Comment by NachoSoto** [comment]
Looking into this. Pretty unfortunate that `ISO8601DateFormatter` inherits from `Formatter` instead of `DateFormatter` and adds its own `func date(from string: String) -> Date?`.

So if we want to pass it around we have to change references to use that.
I think to make this cleaner I'm going to introduce a new `DateFormatterType` protocol that both `DateFormatter` and `ISO8601DateFormatter` conform to, so we don't couple every class in the SDK with the new type, and we can pass any `DateFormatter` as well.
